{{- if not $.Values.DremioAdmin -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dremio-coordinator
  {{- include "dremio.coordinator.annotations" $ | nindent 2 }}
  {{- include "dremio.coordinator.labels" $ | nindent 2 }}
spec:
  serviceName: "dremio-cluster-pod"
  replicas: {{ $.Values.coordinator.count }}
  podManagementPolicy: "Parallel"
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: dremio-coordinator
  {{- include "dremio.coordinator.annotations" $ | nindent 2 }}
  {{- include "dremio.coordinator.labels" $ | nindent 2 }}
  template:
    metadata:
      labels:
        app: dremio-coordinator
        role: dremio-cluster-pod
        {{- include "dremio.coordinator.podLabels" $ | nindent 8 }}
      annotations:
        dremio-configmap/checksum: {{ (tpl ($.Files.Glob "config/*").AsConfig $) | sha256sum }}
        {{- include "dremio.coordinator.podAnnotations" $ | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 120
      {{- include "dremio.coordinator.nodeSelector" $ | nindent 6 }}
      {{- include "dremio.coordinator.tolerations" $ | nindent 6 }}
      containers:
      - name: dremio-coordinator
        image: {{ $.Values.image }}:{{ $.Values.imageTag }}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: {{ $.Values.coordinator.cpu }}
            memory: {{ $.Values.coordinator.memory }}M
        volumeMounts:
        - name: dremio-config
          mountPath: /opt/dremio/conf
        - name: dremio-hive2-config
          mountPath: /opt/dremio/plugins/connectors/hive2.d
        - name: dremio-hive2-config
          mountPath: /opt/dremio/plugins/connectors/hive2-ee.d
        - name: dremio-hive3-config
          mountPath: /opt/dremio/plugins/connectors/hive3.d
        - name: dremio-hive3-config
          mountPath: /opt/dremio/plugins/connectors/hive3-ee.d
        {{- if $.Values.tls.enabled }}
        - name: dremio-tls-coordinator
          mountPath: /opt/dremio/tls
        - name: truststore-with-xyzca
          mountPath: /opt/dremio/tls/trustcacerts
        {{- end }}
        {{- include "dremio.coordinator.extraVolumeMounts" $ | nindent 8 }}
        env:
        {{- if $.Values.tls.enabled }}
        - name: KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dremio-tls-coordinator
              key: keystore-password
        {{- end }}
        - name: DREMIO_MAX_HEAP_MEMORY_SIZE_MB
          value: "{{ template "dremio.coordinator.heapMemory" $ }}"
        - name: DREMIO_MAX_DIRECT_MEMORY_SIZE_MB
          value: "{{ template "dremio.coordinator.directMemory" $ }}"
        - name: DREMIO_JAVA_SERVER_EXTRA_OPTS
          value: >-
            {{- include "dremio.coordinator.extraStartParams" $ | nindent 12 -}}
            -Dzookeeper=zk-hs:2181
            -Dservices.coordinator.enabled=true
            -Dservices.coordinator.master.enabled=false
            -Dservices.coordinator.master.embedded-zookeeper.enabled=false
            -Dservices.executor.enabled=false
            -Dservices.conduit.port=45679
            {{- if $.Values.coordinator.jmx.port }}
            -Dcom.sun.management.jmxremote.port={{ $.Values.coordinator.jmx.port }}
            -Dcom.sun.management.jmxremote.authenticate=false
            -Dcom.sun.management.jmxremote.ssl=false
            {{- end }}
        command: ["/opt/dremio/bin/dremio"]
        args: ["start-fg"]
        ports:
        - containerPort: 31010
          name: client
        - containerPort: 32010
          name: flight
        - containerPort: 45678
          name: server-fabric
        - containerPort: 45679
          name: server-conduit
        readinessProbe:
          httpGet:
            path: /
            {{- if $.Values.tls.enabled }}
            scheme: HTTPS
            {{- end }}
            port: 9047
          initialDelaySeconds: 5
          periodSeconds: 5
      initContainers:
      {{- include "dremio.coordinator.extraInitContainers" $ | nindent 6 }}
      - name: wait-for-dremio-master
        image: docker-upstream.xyz.com/busybox
        command:  ["sh", "-c", "until nc -z dremio-client {{ $.Values.coordinator.web.port }} > /dev/null; do echo Waiting for Dremio master.; sleep 2; done;"]
      volumes:
      - name: dremio-config
        configMap:
          name: dremio-config
      - name: aws-scripts
        configMap:
          name: aws-scripts
      - name: dremio-hive2-config
        configMap:
          name: dremio-hive2-config
      - name: dremio-hive3-config
        configMap:
          name: dremio-hive3-config
      {{- if $.Values.tls.enabled }}
      - name: dremio-tls-coordinator
        secret:
          secretName: dremio-tls-coordinator
          items:
          - key: keystore.jks
            path: keystore.jks
          - key: truststore.jks
            path: truststore.jks
          - key: tls.crt
            path: tls.crt
      - name: truststore-with-xyzca
        secret:
          secretName: truststore-with-xyzca
          items:
          - key: truststore.jks
            path: truststore.jks
      {{- end }}
      {{- include "dremio.coordinator.extraVolumes" $ | nindent 6 }}
      {{- include "dremio.imagePullSecrets" $ | nindent 6}}
{{- end -}}