{{- if not $.Values.DremioAdmin -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dremio-master
  {{- include "dremio.coordinator.annotations" $ | nindent 2}}
  {{- include "dremio.coordinator.labels" $ | nindent 2}}
spec:
  serviceName: "dremio-cluster-pod"
  podManagementPolicy: "Parallel"
  replicas: 1
  selector:
    matchLabels:
      app: dremio-coordinator
  {{- include "dremio.coordinator.annotations" $ | nindent 2}}
  {{- include "dremio.coordinator.labels" $ | nindent 2}}
  template:
    metadata:
      labels:
        app: dremio-coordinator
        role: dremio-cluster-pod
        {{- include "dremio.coordinator.podLabels" $ | nindent 8}}
      annotations:
        dremio-configmap/checksum: {{ (tpl ($.Files.Glob "config/*").AsConfig $) | sha256sum }}
        {{- include "dremio.coordinator.podAnnotations" $ | nindent 8}}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - dremio-coordinator
              topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 120
      {{- include "dremio.coordinator.nodeSelector" $ | nindent 6 }}
      {{- include "dremio.coordinator.tolerations" $ | nindent 6 }}
      containers:
      - name: dremio-master-coordinator
        image: {{ $.Values.image }}:{{ $.Values.imageTag }}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: {{ $.Values.coordinator.cpu }}
            memory: {{ $.Values.coordinator.memory }}M
        volumeMounts:
        - name: dremio-master-volume
          mountPath: /opt/dremio/data
        - name: dremio-config
          mountPath: /opt/dremio/conf
        - name: dremio-hive2-config
          mountPath: /opt/dremio/plugins/connectors/hive2.d
        - name: dremio-hive2-config
          mountPath: /opt/dremio/plugins/connectors/hive2-ee.d
        - name: dremio-hive3-config
          mountPath: /opt/dremio/plugins/connectors/hive3.d
        - name: dremio-hive3-config
          mountPath: /opt/dremio/plugins/connectors/hive3-ee.d
        {{- if $.Values.tls.enabled }}
        - name: dremio-tls-coordinator
          mountPath: /opt/dremio/tls
        - name: truststore-with-xyzca
          mountPath: /opt/dremio/tls/trustcacerts
        {{- end }}
        {{- include "dremio.coordinator.extraVolumeMounts" $ | nindent 8 }}
        env:
        {{- if $.Values.tls.enabled }}
        - name: KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dremio-tls-coordinator
              key: keystore-password
        {{- end }}
        - name: DREMIO_MAX_HEAP_MEMORY_SIZE_MB
          value: "{{ template "dremio.coordinator.heapMemory" $ }}"
        - name: DREMIO_MAX_DIRECT_MEMORY_SIZE_MB
          value: "{{ template "dremio.coordinator.directMemory" $ }}"
        - name: DREMIO_JAVA_SERVER_EXTRA_OPTS
          value: >-
            {{- include "dremio.coordinator.extraStartParams" $ | nindent 12 -}}
            -Dzookeeper=zk-hs:2181
            -Dservices.coordinator.enabled=true
            -Dservices.coordinator.master.enabled=true
            -Dservices.coordinator.master.embedded-zookeeper.enabled=false
            -Dservices.executor.enabled=false
            -Dservices.conduit.port=45679
            {{- if $.Values.coordinator.jmx.port }}
            -Dcom.sun.management.jmxremote.port={{ $.Values.coordinator.jmx.port }}
            -Dcom.sun.management.jmxremote.authenticate=false
            -Dcom.sun.management.jmxremote.ssl=false
            {{- end }}
        command: ["/opt/dremio/bin/dremio"]
        args:
        - "start-fg"
        ports:
        - containerPort: 9047
          name: web
        - containerPort: 31010
          name: client
        - containerPort: 32010
          name: flight
        - containerPort: 45678
          name: server-fabric
        - containerPort: 45679
          name: server-conduit
        {{- if $.Values.coordinator.jmx.port }}
        - containerPort: {{ $.Values.coordinator.jmx.port }}
          name: jmx
        {{- end }}
        readinessProbe:
          httpGet:
            path: /
            {{- if $.Values.tls.enabled }}
            scheme: HTTPS
            {{- end }}
            port: 9047
          initialDelaySeconds: 5
          periodSeconds: 5
      {{- if $.Values.coordinator.syncQueriesJson }}
      - name: sync-query-files
        image: docker.xyz.com/gbidl-dremio/aws/aws-cli:2.1.35
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command: ['sh', '-c', 'sh /home/user/sync-queries-json.sh {{ $.Values.coordinator.syncQueriesJsonLocation }}/$HOSTNAME once']
        resources:
          requests:
            memory: 500M
            cpu: "0.5"
        volumeMounts:
          - name: aws-scripts
            mountPath: /home/user
          - name: dremio-master-volume
            mountPath: /opt/dremio/data
        command: ['sh', '-c', 'sh /home/user/sync-queries-json.sh {{ $.Values.coordinator.syncQueriesJsonLocation }}/$HOSTNAME {{ $.Values.coordinator.syncQueriesJsonInterval }}']
      {{- end }}
      {{- if $.Values.syncLogs }}
      - name: sync-logs
        image: docker.xyz.com/gbidl-dremio/aws/aws-cli:2.1.35
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command: ['sh', '-c', 'sh /home/user/sync-logs.sh {{ $.Values.syncLogsLocation }}/$HOSTNAME once']
        resources:
          requests:
            memory: 500M
            cpu: "0.5"
        volumeMounts:
          - name: aws-scripts
            mountPath: /home/user
          - name: dremio-master-volume
            mountPath: /opt/dremio/data
        command: ['sh', '-c', 'sh /home/user/sync-logs.sh {{ $.Values.syncLogsLocation }}/$HOSTNAME {{ $.Values.syncLogsInterval }}']
      {{- end }}
      initContainers:
      {{- include "dremio.coordinator.extraInitContainers" $ | nindent 6 }}
      - name: start-only-one-dremio-master
        image: docker-upstream.xyz.com/busybox
        command: ["sh", "-c", "INDEX=${HOSTNAME##*-}; if [ $INDEX -ne 0 ]; then echo Only one master should be running.; exit 1; fi; "]
      - name: wait-for-zookeeper
        image: docker-upstream.xyz.com/busybox
        command:  ["sh", "-c", "until ping -c 1 -W 1 zk-hs > /dev/null; do echo Waiting for Zookeeper to be ready.; sleep 2; done;"]
      - name: dremio-log-directory
        image: {{ $.Values.image }}:{{ $.Values.imageTag }}
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: dremio-master-volume
          mountPath: /opt/dremio/data
        command: ["sh", "-c", "mkdir -p /opt/dremio/data/log; chown dremio:dremio /opt/dremio/data/log"]
      - name: chown-data-directory
        image: {{ $.Values.image }}:{{ $.Values.imageTag }}
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: dremio-master-volume
          mountPath: /opt/dremio/data
        command: ["chown"]
        args:
        - "dremio:dremio"
        - "/opt/dremio/data"
      - name: upgrade-task
        image: {{ $.Values.image }}:{{ $.Values.imageTag }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: dremio-master-volume
          mountPath: /opt/dremio/data
        command: ["/opt/dremio/bin/dremio-admin"]
        args:
        - "upgrade"
      volumes:
      - name: dremio-config
        configMap:
          name: dremio-config
      - name: dremio-hive2-config
        configMap:
          name: dremio-hive2-config
      - name: dremio-hive3-config
        configMap:
          name: dremio-hive3-config
      - name: aws-scripts
        configMap:
          name: aws-scripts   
      {{- if $.Values.tls.enabled }}
      - name: dremio-tls-coordinator
        secret:
          secretName: dremio-tls-coordinator
          items:
          - key: keystore.jks
            path: keystore.jks
          - key: truststore.jks
            path: truststore.jks
          - key: tls.crt
            path: tls.crt
      - name: truststore-with-xyzca
        secret:
          secretName: truststore-with-xyzca
          items:
          - key: truststore.jks
            path: truststore.jks
      {{- end }}
      {{- include "dremio.coordinator.extraVolumes" $ | nindent 6 }}
      {{- include "dremio.imagePullSecrets" $ | nindent 6 }}
  volumeClaimTemplates:
  - metadata:
      name: dremio-master-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      {{- include "dremio.coordinator.storageClass" $ | nindent 6 }}
      resources:
        requests:
          storage: {{ $.Values.coordinator.volumeSize }}
{{- end -}}
