# The Dremio image used in the cluster.
#
# It is *highly* recommended to update the version tag to
# the version that you are using. This will ensure that all
# the pods are using the same version of the software.
#
# Using latest will cause Dremio to potentially upgrade versions
# automatically during redeployments and may negatively impact
# the cluster.
image: docker.xyz.com/gbidl-dremio/dremio-ee
imageTag: 13.0.0-teradata
#image: dremio/dremio-ee
#imageTag: 13.0.0

# Enable TLS for the whole cluster
tls:
  enabled: true

# Custom parameters - used to copy server logs to S3 location
syncLogs: false
syncLogsLocation: s3://dremio-internal-bucket/sales/logs/server_logs
syncLogsInterval: 60

# Dremio Coordinator
coordinator:
  cpu: 18
  memory: 20000

  # This count is used for slave coordinators only.
  count: 0

  # Coordinator data volume size (applies to the master coordinator only).
  volumeSize: 500Gi

  # Secret to be used for TLS
  tls:
    secret: dremio-tls-coordinator

  # xyz Private CA
  podAnnotations:
    cmcs.crypto-services.xyz.com/tls-server-client-issuer: "{\"name\":\"dremio-test-ca\",\"kind\":\"xyzCertificateManagerPrivateCA\"}"
    cmcs.crypto-services.xyz.com/tls-server-client-issuer-secret-name: dremio-tls-coordinator
    cmcs.crypto-services.xyz.com/trusted-ca-list: '[{"kind":"xyzCertificateManagerPrivateCA"}]'
    cmcs.crypto-services.xyz.com/key-type: RSA-2048
    cmcs.crypto-services.xyz.com/keystore-type: jks

  # Changed to write logs to console
  extraStartParams: >-
    -Ddremio.log.path=/opt/dremio/data/log
    -XX:+PrintClassHistogramBeforeFullGC

  # Web UI
  web:
    port: 9047

  # ODBC/JDBC Client
  client:
    port: 31010

  # JMX
  jmx:
    port: 9000

  # Custom parameters - used to copy queries.json to S3 location
  syncQueriesJson: false
  syncQueriesJsonLocation: s3://dremio-internal-bucket/sales/logs/query_logs
  syncQueriesJsonInterval: 60

  # Flight Client
  flight:
    port: 32010
# Dremio Executor
executor:
  cpu: 18
  memory: 20000

  # Engines
  # Engine names be 47 characters or less and be lowercase alphanumber characters or '-'.
  engines: ["tst-accl","tst-query"]
  count: 0

  # Executor volume size.
  volumeSize: 100Gi

 # Secret to be used for TLS
  tls:
    secret: dremio-tls-executor

  # xyz Private CA
  podAnnotations:
    cmcs.crypto-services.xyz.com/tls-server-client-issuer: "{\"name\":\"dremio-test-ca\",\"kind\":\"xyzCertificateManagerPrivateCA\"}"
    cmcs.crypto-services.xyz.com/tls-server-client-issuer-secret-name: dremio-tls-executor
    cmcs.crypto-services.xyz.com/trusted-ca-list: '[{"kind":"xyzCertificateManagerPrivateCA"}]'
    cmcs.crypto-services.xyz.com/key-type: RSA-2048
    cmcs.crypto-services.xyz.com/keystore-type: jks

  # Uncomment the lines below to use a custom set of extra startup parameters for executors.
  extraStartParams: >-
    -Xloggc:/opt/dremio/data/gc.log
    -XX:+UseGCLogFileRotation
    -XX:NumberOfGCLogFiles=5
    -XX:GCLogFileSize=4000k
    -XX:+PrintClassHistogramBeforeFullGC
    -XX:+PrintClassHistogramAfterFullGC
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:HeapDumpPath=/opt/dremio/data
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:MaxGCPauseMillis=500
    -XX:InitiatingHeapOccupancyPercent=25
    -XX:ErrorFile=/opt/dremio/data/hs_err_pid%p.log
    -Dzookeeper=zk-hs:2181
    -Dservices.coordinator.enabled=false
    -Ddremio.log.path=/opt/dremio/data/log

  # Dremio C3
  # Designed for use with NVMe storage devices, performance may be impacted when using
  # persistent volume storage that resides far from the physical node.
  cloudCache:
    enabled: false

    # Volumes to use for C3, specify multiple volumes if there are more than one local
    # NVMe disk that you would like to use for C3.
    volumes:
    - name: "c3-default-disk1"
      size: 50Gi
      storageClass: "gp2"
    - name: "c3-default-disk2"
      size: 50Gi
      storageClass: "gp2"

  # Gandiva Cache
  # Designed for use with SSD storage devices (NVMe is not officially supported), performance may be impacted when using
  # persistent volume storage that resides far from the physical node.
  gandivaCache:
    enabled: false

    # Volume to use for Gandiva Cache, specify only one volume
    volumes:
    - name: "gandiva-default-disk1"
      size: 10Gi
      storageClass: "gp2"

    # Cache size
    size: 1600
    # Cache location in S3, this file is generated by setting special support flags and running queries, with just one
    # executor enabled
    prewarmFile: s3://gbidl-us-west-2-dev-dremio/gandiva-cache/test.tar

  # Engine Overrides
  #
  # The settings above are overridable on a per-engine basis. These
  # values here will take precedence and *override* the configured values
  # on a per-engine basis. Engine ovrrides are matched with the name in the above
  # list of engines.
  #
  # Special per-engine parameters:
  # volumeClaimName: For each engine, you can optionally specify a value for the volume claim name,
  #   this value must be unique to each engine or may cause unintended consequences. This value is
  #   primarily intended for transitioning an existing single engine to a multi-engine configuration
  #   where there may already have been existing persistent volumes.
  #

  engineOverride:
    tst-accl:
      count: 0
    tst-query:
      count: 1
  #   asc:
  #     volumeSize:
  #     count: 1
  #     volumeClaimName: dremio-executor-query-engine-volume
  #     gandivaCache:
  #       enabled: true
  #       size: 3000
  #       prewarmFile: s3://manoj-gandiva-cache/gandiva-cache/gandiva-cache-v2.tar
  #       volumes:
  #         - name: "gandiva-query-engine-disk1"
  #           size: 20Gi
  #           storageClass: "gp2"
  #     cloudCache:
  #       enabled: true
  #       volumes:
  #         - name: "c3-query-engine-disk1"
  #           size: 50Gi
  #           storageClass: "gp2"
  #         - name: "c3-query-engine-disk2"
  #           size: 50Gi
  #           storageClass: "gp2"

# Zookeeper
zookeeper:
  # The Zookeeper image used in the cluster.
  image: k8s.gcr.io/kubernetes-zookeeper
  imageTag: 1.0-3.4.10

  cpu: 0.5
  memory: 1024
  count: 3

  volumeSize: 10Gi


# Control where uploaded files are stored for Dremio.
# For more information, see https://docs.dremio.com/deployment/distributed-storage.html
distStorage:
  type: "aws"

  aws:
    bucketName: "dremio-internal-bucket"
    path: "/sales"
    authentication: "metadata"

    extraProperties: |
      <property>
        <name>fs.s3a.endpoint</name>
        <value>s3.us-west-2.amazonaws.com</value>
      </property>
      <property>
        <name>dremio.pdfs.remote.rpc.timeout.ms</name>
        <value>30000</value>
      </property>
      <property>
        <name>dremio.s3.region</name>
        <value>us-west-2</value>
      </property>
      <property>
        <name>dremio.s3.compat</name>
        <description>Compatiable mode, not calling AWS STS</description>
      <value>true</value>
      </property>
      <property>
        <name>fs.s3a.assumed.role.sts.endpoint</name>
        <value>sts.us-west-2.amazonaws.com</value>
      </property>
      <property>
        <name>fs.s3a.assumed.role.sts.endpoint.region</name>
        <value>us-west-2</value>
      </property>
      <property>
        <name>dremio.s3.whitelisted.buckets</name>
        <value>dremio-internal-bucket</value>
      </property>
      <property>
        <name>fs.s3a.connection.ssl.enabled</name>
        <value>true</value>
      </property>
      <property>
        <name>fs.s3a.server-side-encryption-algorithm</name>
        <value>SSE-KMS</value>
      </property>
      <property>
        <name>fs.s3a.server-side-encryption.key</name>
        <value>arn:aws:kms:us-west-2:608633355463:key/4911703f-474a-49d4-9bbf-a2c8526eb5d0</value>
      </property>

service:
  type: LoadBalancer

  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb

  internalLoadBalancer: true
  #loadBalancerIP: 0.0.0.0

imagePullSecrets:
  - dremio-docker-secret
